language: scala
sudo: required
jdk:
- oraclejdk8
scala:
- 2.11.8
services:
- postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.3
env:
  global:
  - PG_USER=postgres
  - PG_PASSWORD=""
  - PG_DBNAME="jdbc:postgresql://127.0.0.1/appschemadev"
before_script:
- export DEBIAN_FRONTEND=noninteractive;
  sudo -E apt-get -yq update &>> ~/apt-get-update.log;
  sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.3
- psql -c 'create database appschemadev;' -U postgres
- psql -U postgres -c "create extension postgis"
script:
- sbt compile
- sbt jetty:start && sleep 10
- sbt test
- sbt jetty:stop
# makeSite
before_install:
#- openssl aes-256-cbc -K $encrypted_bfe1df66c3c1_key -iv $encrypted_bfe1df66c3c1_iv
#  -in ghpages_ecdsa_sacback.enc -out ghpages_ecdsa_sacback -d
after_success:
#- chmod 600 ghpages_ecdsa_sacback && eval `ssh-agent -s` && ssh-add ghpages_ecdsa_sacback
#- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt ghpagesPushSite

notifications:
  email:
  - allixender@gmail.com
